### ISSUE TITLE
[BUG] vicos-client-cli doesn't compile because dependency doesn't exist

### ISSUE THREAD

**Issue by mercuriete** [ibm-research/vicos#1]
apache jclouds api swift 2.0.0-SNAPSHOT is not in jcenter neither maven central.

'org.apache.jclouds.api:swift:2.0.0-SNAPSHOT'

offending line:
https://github.com/ibm-research/vicos/blob/master/vicos-client-cli/build.gradle#L18

please change the dependency to 1.9.3
compile group: 'org.apache.jclouds.api', name: 'swift', version: '1.9.3'

I can do a pull request if you wish.

Thanks.

**Comment by mbrandenburger** [comment]
Thanks for catching this! Fixed!
